name: Fetch FreeFire Stats

on:
  workflow_dispatch:
    inputs:
      uid:
        description: 'Free Fire UID'
        required: true
        type: string

jobs:
  run-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          python main.py --uid "${{ github.event.inputs.uid }}"
